// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_menu

import (
	"github.com/iimeta/fastapi-admin/api/sys_menu"
)

type ControllerV1 struct{}

func NewV1() sys_menu.ISysMenuV1 {
	return &ControllerV1{}
}
