// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package task_video

import (
	"github.com/iimeta/fastapi-admin/v2/api/task_video"
)

type ControllerV1 struct{}

func NewV1() task_video.ITaskVideoV1 {
	return &ControllerV1{}
}
