// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package text

import (
	"github.com/iimeta/fastapi-admin/api/text"
)

type ControllerV1 struct{}

func NewV1() text.ITextV1 {
	return &ControllerV1{}
}
