// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package log_file

import (
	"github.com/iimeta/fastapi-admin/v2/api/log_file"
)

type ControllerV1 struct{}

func NewV1() log_file.ILogFileV1 {
	return &ControllerV1{}
}
