// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_settings

import (
	"github.com/iimeta/fastapi-admin/api/sys_settings"
)

type ControllerV1 struct{}

func NewV1() sys_settings.ISysSettingsV1 {
	return &ControllerV1{}
}
