// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notice_template

import (
	"github.com/iimeta/fastapi-admin/v2/api/notice_template"
)

type ControllerV1 struct{}

func NewV1() notice_template.INoticeTemplateV1 {
	return &ControllerV1{}
}
