// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package log_text

import (
	"github.com/iimeta/fastapi-admin/api/log_text"
)

type ControllerV1 struct{}

func NewV1() log_text.ILogTextV1 {
	return &ControllerV1{}
}
