// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package task_file

import (
	"github.com/iimeta/fastapi-admin/api/task_file"
)

type ControllerV1 struct{}

func NewV1() task_file.ITaskFileV1 {
	return &ControllerV1{}
}
