// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package open

import (
	"github.com/iimeta/fastapi-admin/v2/api/open"
)

type ControllerV1 struct{}

func NewV1() open.IOpenV1 {
	return &ControllerV1{}
}
