// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package group

import (
	"github.com/iimeta/fastapi-admin/api/group"
)

type ControllerV1 struct{}

func NewV1() group.IGroupV1 {
	return &ControllerV1{}
}
