// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package task_batch

import (
	"github.com/iimeta/fastapi-admin/api/task_batch"
)

type ControllerV1 struct{}

func NewV1() task_batch.ITaskBatchV1 {
	return &ControllerV1{}
}
