// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_config

import (
	"github.com/iimeta/fastapi-admin/v2/api/sys_config"
)

type ControllerV1 struct{}

func NewV1() sys_config.ISysConfigV1 {
	return &ControllerV1{}
}
