// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package log_midjourney

import (
	"github.com/iimeta/fastapi-admin/api/log_midjourney"
)

type ControllerV1 struct{}

func NewV1() log_midjourney.ILogMidjourneyV1 {
	return &ControllerV1{}
}
