// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package log_batch

import (
	"github.com/iimeta/fastapi-admin/api/log_batch"
)

type ControllerV1 struct{}

func NewV1() log_batch.ILogBatchV1 {
	return &ControllerV1{}
}
