// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package log_general

import (
	"github.com/iimeta/fastapi-admin/api/log_general"
)

type ControllerV1 struct{}

func NewV1() log_general.ILogGeneralV1 {
	return &ControllerV1{}
}
