// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sys_admin

import (
	"github.com/iimeta/fastapi-admin/v2/api/sys_admin"
)

type ControllerV1 struct{}

func NewV1() sys_admin.ISysAdminV1 {
	return &ControllerV1{}
}
