// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package invite

import (
	"github.com/iimeta/fastapi-admin/v2/api/invite"
)

type ControllerV1 struct{}

func NewV1() invite.IInviteV1 {
	return &ControllerV1{}
}
