// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package app

import (
	"github.com/iimeta/fastapi-admin/api/app"
)

type ControllerV1 struct{}

func NewV1() app.IAppV1 {
	return &ControllerV1{}
}
