// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package site_config

import (
	"github.com/iimeta/fastapi-admin/api/site_config"
)

type ControllerV1 struct{}

func NewV1() site_config.ISiteConfigV1 {
	return &ControllerV1{}
}
