// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"github.com/iimeta/fastapi-admin/api/chat"
)

type ControllerV1 struct{}

func NewV1() chat.IChatV1 {
	return &ControllerV1{}
}
