// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package log_audio

import (
	"github.com/iimeta/fastapi-admin/api/log_audio"
)

type ControllerV1 struct{}

func NewV1() log_audio.ILogAudioV1 {
	return &ControllerV1{}
}
