// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package provider

import (
	"github.com/iimeta/fastapi-admin/api/provider"
)

type ControllerV1 struct{}

func NewV1() provider.IProviderV1 {
	return &ControllerV1{}
}
