// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin_user

import (
	"github.com/iimeta/fastapi-admin/v2/api/admin_user"
)

type ControllerV1 struct{}

func NewV1() admin_user.IAdminUserV1 {
	return &ControllerV1{}
}
