// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package task_image

import (
	"github.com/iimeta/fastapi-admin/v2/api/task_image"
)

type ControllerV1 struct{}

func NewV1() task_image.ITaskImageV1 {
	return &ControllerV1{}
}
