// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"github.com/iimeta/fastapi-admin/v2/api/model"
)

type ControllerV1 struct{}

func NewV1() model.IModelV1 {
	return &ControllerV1{}
}
