// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model_agent

import (
	"github.com/iimeta/fastapi-admin/api/model_agent"
)

type ControllerV1 struct{}

func NewV1() model_agent.IModelAgentV1 {
	return &ControllerV1{}
}
