// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ticket

import (
	"github.com/iimeta/fastapi-admin/v2/api/ticket"
)

type ControllerV1 struct{}

func NewV1() ticket.ITicketV1 {
	return &ControllerV1{}
}
