// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package corp

import (
	"github.com/iimeta/fastapi-admin/api/corp"
)

type ControllerV1 struct{}

func NewV1() corp.ICorpV1 {
	return &ControllerV1{}
}
