// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package finance

import (
	"github.com/iimeta/fastapi-admin/v2/api/finance"
)

type ControllerV1 struct{}

func NewV1() finance.IFinanceV1 {
	return &ControllerV1{}
}
