// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package app_key

import (
	"github.com/iimeta/fastapi-admin/v2/api/app_key"
)

type ControllerV1 struct{}

func NewV1() app_key.IAppKeyV1 {
	return &ControllerV1{}
}
