// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notice

import (
	"github.com/iimeta/fastapi-admin/v2/api/notice"
)

type ControllerV1 struct{}

func NewV1() notice.INoticeV1 {
	return &ControllerV1{}
}
