// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package key

import (
	"github.com/iimeta/fastapi-admin/api/key"
)

type ControllerV1 struct{}

func NewV1() key.IKeyV1 {
	return &ControllerV1{}
}
