// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin_reseller

import (
	"github.com/iimeta/fastapi-admin/api/admin_reseller"
)

type ControllerV1 struct{}

func NewV1() admin_reseller.IAdminResellerV1 {
	return &ControllerV1{}
}
