// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package statistics

import (
	"github.com/iimeta/fastapi-admin/v2/api/statistics"
)

type ControllerV1 struct{}

func NewV1() statistics.IStatisticsV1 {
	return &ControllerV1{}
}
