// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package log_video

import (
	"github.com/iimeta/fastapi-admin/v2/api/log_video"
)

type ControllerV1 struct{}

func NewV1() log_video.ILogVideoV1 {
	return &ControllerV1{}
}
